# Generated by Django 4.2.1 on 2023-06-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aramex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyNum', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('shippingFrom', models.CharField(max_length=200)),
                ('senderName', models.CharField(max_length=200)),
                ('senderNumber', models.CharField(max_length=200)),
                ('shippingTo', models.CharField(max_length=200)),
                ('receiverName', models.CharField(max_length=200)),
                ('receiverNumber', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('canBeCanceled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('customerName', models.CharField(default='', max_length=200)),
                ('customerNumber', models.CharField(default='', max_length=200)),
                ('orderCreated', models.DateTimeField(auto_now_add=True)),
                ('shippingFrom', models.CharField(max_length=200)),
                ('shippingTo', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('courier', models.CharField(blank=True, max_length=200)),
                ('policyNum', models.CharField(blank=True, max_length=200)),
                ('waybillCreated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Smsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyNum', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('shippingFrom', models.CharField(max_length=200)),
                ('senderName', models.CharField(max_length=200)),
                ('senderNumber', models.CharField(max_length=200)),
                ('shippingTo', models.CharField(max_length=200)),
                ('receiverName', models.CharField(max_length=200)),
                ('receiverNumber', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('canBeCanceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyNum', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('shippingFrom', models.CharField(max_length=200)),
                ('senderName', models.CharField(max_length=200)),
                ('senderNumber', models.CharField(max_length=200)),
                ('shippingTo', models.CharField(max_length=200)),
                ('receiverName', models.CharField(max_length=200)),
                ('receiverNumber', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('canBeCanceled', models.BooleanField(default=True)),
            ],
        ),
    ]
